version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dampess
      POSTGRES_PASSWORD: dgRGQEGGR55<ยง
      POSTGRES_DB: appli-gestion-sport
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
