version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: back-end
    environment:
      POSTGRES_USER: dampess
      POSTGRES_PASSWORD: dgRGQEGGR55<ยง
      POSTGRES_DB: appli-gestion-sport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
